/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.9 2005/01/07 09:37:18 dts12 Exp $
 */
#ifndef POWERGURU_H
#define POWERGURU_H

/*
 * function declarations 
 */
void            init_powerguru(void);
Netsnmp_Node_Handler handle_powerGuruDataLog;
Netsnmp_Node_Handler handle_powerGuruUnitAddress;
Netsnmp_Node_Handler handle_powerGuruChargeAmps;
Netsnmp_Node_Handler handle_powerGuruPVAmps;
Netsnmp_Node_Handler handle_powerGuruPVVolts;
Netsnmp_Node_Handler handle_powerGuruDailyKW;
Netsnmp_Node_Handler handle_powerGuruAuxMode;
Netsnmp_Node_Handler handle_powerGuruErrorMode;
Netsnmp_Node_Handler handle_powerGuruChargerMode;
Netsnmp_Node_Handler handle_powerGuruBatteryVolts;
Netsnmp_Node_Handler handle_powerGuruLoadAmps;
Netsnmp_Node_Handler handle_powerGuruACBuyAmps;
Netsnmp_Node_Handler handle_powerGuruACInputVolts;
Netsnmp_Node_Handler handle_powerGuruACOutputVolts;
Netsnmp_Node_Handler handle_powerGuruACSellAmps;

#endif                          /* POWERGURU_H */
 
