/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.9 2005/01/07 09:37:18 dts12 Exp $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xantrex.h"

/** Initializes the xantrex module */
void
init_xantrex(void)
{

    DEBUGMSGTL(("xantrex", "Initializing\n"));

}

// local Variables:
// mode: C++
// indent-tabs-mode: nil
// End:
