// 
// Copyright (C) 2018 Free Software Foundation, Inc.
// 
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

#ifdef HAVE_CONFIG_H
// This is generated by autoconf.
# include "config.h"
#endif

#include <cstring>
#include <vector>
#include <stdlib.h>
#include <unistd.h>
#include <termios.h>
#include <sstream>
#include <signal.h>
#include <errno.h>
#include <thread>
#include <condition_variable>
#include <mutex>
#include <chrono>

#ifdef HAVE_GETOPT_H
#include <getopt.h>
#else
extern int optind;
extern char *optarg;
#endif

#include "log.h"
#include "err.h"
#include "ownet.h"
#include "console.h"
#include "database.h"

extern LogFile dbglogfile;

using namespace std::chrono_literals;

#if 0
void
console_handler(Console &con)
{
    DEBUGLOG_REPORT_FUNCTION;
    while ((ch = con.Getc()) != 'q') {
        if (ch > 0) {                // If we have something, process it
            con.Putc (ch);          // echo inputted character to screen
            switch (ch) {
              case 'Q':
              case 'q':
                  con.Puts("Qutting PowerGuru due to user input!\n");
                  msg.writeNet("quit");
                  con.Reset();
                  exit(0);
                  break;
              case '?':
                  con.Puts("PowerGuru client\n");
                  con.Puts("\t? - help\r\n");
                  con.Puts("\tq - Quit\r\n");
                  con.Puts("\tQ - Quit\r\n");
                  sleep(2);
              default:
                  break;
            };
        }

}
#endif

//#if defined(HAVE_LIBPQ) && defined(HAVE_MARIADB)
void
msg_handler(Database &db)
{
    DEBUGLOG_REPORT_FUNCTION;
}
//#endif

#ifdef BUILD_OWNET
void
ownet_handler(pdev::Ownet &ownet)
{
    DEBUGLOG_REPORT_FUNCTION;
    dbglogfile << "PowerGuru - 1 Wire Mode" << std::endl;
    bool poll = true;

    // Open the network connection to the database.
    std::string query = "INSERT INTO onewire VALUES(";
    query += "";
    query += ");";

    std::map<std::string, pdev::ownet_t *> sensors = ownet.getSensors();
    std::map<std::string, pdev::ownet_t *>::iterator it;
    while (ownet.getPollSleep() != 0) {
        for (it = sensors.begin(); it != sensors.end(); it++) {
            if (it->second->family == "10") {
                ownet.getTemperature(it->first.c_str());
            }
        }
        ownet.dump();
        
        // Don't eat up all the cpu cycles!
        std::this_thread::sleep_for(std::chrono::seconds(ownet.getPollSleep()));
    }
}
#endif

#ifdef BUILD_OUTBACK
void
outback_handler(pdev::Ownet &ownet)
{
    DEBUGLOG_REPORT_FUNCTION;

    dbglogfile << "FIXME: outback_handler() unimplementd"<< std::endl;
    // Don't eat up all the cpu cycles!
    std::this_thread::sleep_for(std::chrono::seconds(ownet.getPollSleep()));
}
#endif

#ifdef BUILD_XANTREX
void
xantrex_handler(pdev::Ownet &ownet)
{
    DEBUGLOG_REPORT_FUNCTION;

    dbglogfile << "FIXME: xantrext_handler() unimplemented"<< std::endl;
    // Don't eat up all the cpu cycles!
    std::this_thread::sleep_for(std::chrono::seconds(ownet.getPollSleep()));
}
#endif

// local Variables:
// mode: C++
// indent-tabs-mode: nil
// End:
