// 
// Copyright (C) 2018
//      Free Software Foundation, Inc.
// 
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

#ifndef __COMMANDS_H__
#define __COMMANDS_H__

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include <cstring>
#include <vector>
#include <map>
#include "xml.h"
#include "log.h"

class Commands 
{
 public:
  typedef enum { NOP, LIST, POLL } cmd_t; 
  Commands();
  ~Commands();

  std::string &createCommand(cmd_t cmd, const std::string &args,
                                   std::string &str);
  const std::string &execCommand(XML &xml);
};

#endif	// __COMMANDS_H__

// local Variables:
// mode: C++
// indent-tabs-mode: nil
// End:
