// 
// Copyright (C) 2018
//      Free Software Foundation, Inc.
// 
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include <sys/types.h>
#include <sys/stat.h>

#include <unistd.h>
#include <cstring>
#include <vector>
#include "xml.h"
#include "log.h"
#include "commands.h"

extern LogFile dbglogfile;

Commands::Commands()
{
    DEBUGLOG_REPORT_FUNCTION;
}

Commands::~Commands()
{
    DEBUGLOG_REPORT_FUNCTION;
}

std::string &
Commands::createCommand(cmd_t cmd, const std::string &args,
                        std::string &str)
{
    DEBUGLOG_REPORT_FUNCTION;
    str.clear();
    str = "<command>";
    switch (cmd) {
      case LIST:
          dbglogfile << "LIST command" << std::endl;
          str += "<list>" + args + "</list>";
          break;
      case POLL:
          dbglogfile << "POLL command" << std::endl;  
          str += "<poll>" + args + "</poll>";
          break;
      case NOP:
          dbglogfile << "NOP command" << std::endl;  
          break;
    };
    
    str += "</command>";

    return str;
}

std::string &
parseCommand(XML &xml, std::string &str)
{
    DEBUGLOG_REPORT_FUNCTION;

    return str;
}

// local Variables:
// mode: C++
// indent-tabs-mode: nil
// End:
