// 
// Copyright (C) 2018,2019 Free Software Foundation, Inc.
// 
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

/// \file commands.h Class to create and parse simple XML messages between
///                  the client and the server.

#ifndef __COMMANDS_H__
#define __COMMANDS_H__

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include <cstring>
#include <vector>
#include <map>
#include "xml.h"

class Commands 
{
public:
    typedef enum { NOP, LIST, POLL, HELO, RESULT, EVENT } cmd_t; 
    Commands();
    ~Commands();
    std::string &createNode(cmd_t cmd, const std::string &args,
                               std::string &str);
    std::string &createCommand(cmd_t cmd, const std::string &args,
                               std::string &str);
    std::string &execCommand(XML &xml, std::string &str);
    cmd_t &convertAction(const std::string &cmd) {
        return _commands[cmd];
    };
    
protected:
    std::map<const std::string, cmd_t> _commands;
};

#endif	// __COMMANDS_H__

// local Variables:
// mode: C++
// indent-tabs-mode: nil
// End:
