// 
// Copyright (C) 2005, 2006 - 2018
//      Free Software Foundation, Inc.
// 
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <cstring>
#include <iostream>
#include <fstream>

#include "err.h"
#include "log.h"
#include "rc.h"

using namespace rcinit;
  
RCinitFile::RCinitFile()
{
}

RCinitFile::~RCinitFile()
{
}

// Look for a config file in the likely places.
retcode_t
RCinitFile::load_files()
{
    char *home;
    std::string loadfile;
  
    // Check the default system location
    loadfile = "/etc/powerguru/config";
    parse_file(loadfile);

    // Check the default config location
    loadfile = "/usr/local/etc/powerguru/config";
    parse_file(loadfile);
  
    // Check the users home directory
    home = getenv("HOME");
    if (home) {
        loadfile = home;
        loadfile += "/.powerguru/config";
        return parse_file(loadfile);
    }
  
    return ERROR;
}

// Parse the config file and set the variables.
retcode_t
RCinitFile::parse_file(std::string &filespec)
{
    struct stat stats;
    std::string action;
    std::string variable;
    std::string value;
    std::ifstream in;

    BOOST_LOG(lg) << "Seeing if " << filespec << " exists.";
    if (filespec.size() == 0) {
        return ERROR;
    }
  
    if (stat(filespec.c_str(), &stats) == 0) {
        in.open(filespec.c_str());
    
        if (!in) {
            BOOST_LOG(lg) << "ERROR: Couldn't open file: " << filespec;
            return ERROR;
        }

        // Read in each line and parse it
        while (!in.eof()) {
            // Get the first token
            in >> action;
            // Ignore comment lines
            if (action == "#" ) {
                BOOST_LOG(lg) << "Ignoring comment line ";
                continue;
            }
      
            in >> variable >> value;
            //      BOOST_LOG(lg) << action << variable << value;

            if (action == "set") {
                if (variable == "dbhost") {
                    BOOST_LOG(lg) << "Database host configured to be " << value;
                    _dbhost = value;
                }
                if (variable == "dbuser") {
                    BOOST_LOG(lg) << "Database user configured to be " << value;
                    _dbuser = value;
                }
                if (variable == "dbpasswd") {
                    BOOST_LOG(lg) << "Database password configured to be " << value;
                    _dbpasswd = value;
                }
                if (variable == "dbname") {
                    BOOST_LOG(lg) << "Database name configured to be " << value;
                    _dbname = value;
                }
                if (variable == "devmode") {
                    BOOST_LOG(lg) << "Device mode configured to be " << value;
                    _devmode = value;
                }
                if (variable == "device") {
                    BOOST_LOG(lg) << "Device is " << value;
                    _device = value;
                }
            }
        }
    } else {
        if (in) {
            in.close();
        }
        return ERROR;
    }  

    if (in) {
        in.close();
    }
    return SUCCESS;
}

// Write the changed settings to the config file
retcode_t
RCinitFile::update_file(std::string &filespec)
{
    std::cerr << __PRETTY_FUNCTION__ << "ERROR: unimplemented!" << std::endl;
    return ERROR;
}

// local Variables:
// mode: C++
// indent-tabs-mode: nil
// End:
