// 
// Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013
//               2014, 2015, 2016, 2017, 2018, 2019
//      Free Software Foundation, Inc.
// 
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <cstring>
#include <iostream>
#include <fstream>

#include "log.h"
#include "rc.h"

#include <boost/system/error_code.hpp>
using namespace boost::system;

RCinitFile::RCinitFile(void)
{
    DEBUGLOG_REPORT_FUNCTION;
}

RCinitFile::~RCinitFile(void)
{
    DEBUGLOG_REPORT_FUNCTION;
}

// Look for a config file in the likely places.
boost::system::error_code
RCinitFile::load_files(void)
{
    DEBUGLOG_REPORT_FUNCTION;

    char *home;
    std::string loadfile;
  
    // Check the default system location
    loadfile = "/etc/powerguru/config";
    parse_file(loadfile);

    // Check the default config location
    loadfile = "/usr/local/etc/powerguru/config";
    parse_file(loadfile);
  
    // Check the users home directory
    home = getenv("HOME");
    if (home) {
        loadfile = home;
        loadfile += "/.powerguru/config";
        return parse_file(loadfile);
    }
  
    return errc::make_error_code(errc::not_supported);
}

// Parse the config file and set the variables.
boost::system::error_code
RCinitFile::parse_file(const std::string &filespec)
{
    DEBUGLOG_REPORT_FUNCTION;

    struct stat stats;
    std::string action;
    std::string variable;
    std::string value;
    std::ifstream in;

     BOOST_LOG(lg) << "Seeing if " << filespec << " exists.";
    if (filespec.size() == 0) {
         _errorcode = errc::make_error_code(errc::not_supported);
         return _errorcode;
    }
  
    if (stat(filespec.c_str(), &stats) == 0) {
        in.open(filespec.c_str());
    
        if (!in) {
            BOOST_LOG(lg) << "ERROR: Couldn't open file: " << filespec;
            _errorcode = errc::make_error_code(errc::not_supported);
            return _errorcode;
        }

        // Read in each line and parse it
        while (!in.eof()) {
            // Get the first token
            in >> action;
            // Ignore comment lines
            if (action == "#" ) {
                BOOST_LOG(lg) << "Ignoring comment line ";
                continue;
            }
      
            in >> variable >> value;
            //      BOOST_LOG(lg) << action << variable << value;

            if (action == "set") {
                if (variable == "dbhost") {
                    BOOST_LOG(lg) << "Database host configured to be " << value;
                    _dbhost = value;
                }
                if (variable == "dbuser") {
                    BOOST_LOG(lg) << "Database user configured to be " << value;
                    _dbuser = value;
                }
                if (variable == "dbpasswd") {
                    BOOST_LOG(lg) << "Database password configured to be " << value;
                    _dbpasswd = value;
                }
                if (variable == "dbname") {
                    BOOST_LOG(lg) << "Database name configured to be " << value;
                    _dbname = value;
                }
                if (variable == "devmode") {
                    BOOST_LOG(lg) << "Device mode configured to be " << value;
                    _devmode = value;
                }
                if (variable == "device") {
                    BOOST_LOG(lg) << "Device is " << value;
                    _device = value;
                }
            }
        }
    } else {
        if (in) {
            in.close();
        }
        _errorcode = errc::make_error_code(errc::not_supported);
        return _errorcode;
    }  

    if (in) {
        in.close();
    }
    _errorcode = errc::make_error_code(errc::success);
    return _errorcode;
}

// Write the changed settings to the config file
boost::system::error_code
RCinitFile::update_file(const std::string &filespec)
{
    std::cerr << __PRETTY_FUNCTION__ << "ERROR: unimplemented!" << std::endl;
    _errorcode = errc::make_error_code(errc::not_supported);
    return _errorcode;
}

// local Variables:
// mode: C++
// indent-tabs-mode: nil
// End:
