// 
// Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013
//               2014, 2015, 2016, 2017, 2018, 2019
//      Free Software Foundation, Inc.
// 
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

#ifndef __RC_H__
#define __RC_H__

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include <cstring>
#include <boost/system/error_code.hpp>

class RCinitFile 
{
public:
    RCinitFile();
    ~RCinitFile();
    boost::system::error_code load_files();
    boost::system::error_code parse_file(const std::string &filespec);
    boost::system::error_code update_file(const std::string &filespec);

    // Database config options
    std::string dbhostGet(void)   { return _dbhost; }
    std::string dbuserGet(void)   { return _dbuser; };
    std::string dbpasswdGet(void) { return _dbpasswd; };
    std::string dbnameGet(void)   { return _dbname; };
    std::string devmodeGet(void)  { return _devmode; };
    std::string deviceGet(void)   { return _device; };

private:
    std::string _filespec;
    std::string _dbhost;
    std::string _dbuser;
    std::string _dbpasswd;
    std::string _dbname;
    std::string _devmode;
    std::string _device;
    boost::system::error_code _errorcode;
}; 

// __RC_H__
#endif

// local Variables:
// mode: C++
// indent-tabs-mode: nil
// End:
