// 
// Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010 Free Software Foundation, Inc.
// 
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

#ifndef __RC_H__
#define __RC_H__

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include <string>
#include "err.h"

namespace rcinit {
  
class RCinitFile 
{
 public:
  RCinitFile();
  ~RCinitFile();
  retcode_t load_files();
  retcode_t parse_file(std::string filespec);
  retcode_t update_file(std::string filespec);

  // Database config options
  std::string dbhostGet()   { return _dbhost; }
  std::string dbuserGet()   { return _dbuser; };
  std::string dbpasswdGet() { return _dbpasswd; };
  std::string dbnameGet()   { return _dbname; };
  std::string devmodeGet()  { return _devmode; };
  std::string deviceGet()   { return _device; };

 private:
  std::string _filespec;
  std::string _dbhost;
  std::string _dbuser;
  std::string _dbpasswd;
  std::string _dbname;
  std::string _devmode;
  std::string _device;
}; 

// End of rcinit namespace 
}

// __RC_H__
#endif
