// 
//   Copyright (C) 2018, 2019 Free Software Foundation, Inc.
//
//   This program is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation; either version 2 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the Free Software
//   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include <unistd.h>
#include <vector>
#include "dejagnu.h"
#include "database.h"
#include "log.h"
#include <boost/regex.hpp>

int verbosity;
static void usage (void);
bool waitforgdb = false;

TestState runtest;

Database::Database() {
    DEBUGLOG_REPORT_FUNCTION;
};

Database::~Database() {
        DEBUGLOG_REPORT_FUNCTION;
};

// Declare a class inherited from the base class so we can access the internal
// protected data.
class Test : public Database {
public:
    Test() {
        DEBUGLOG_REPORT_FUNCTION;

        // Test creating commands
        std::string result;
        std::cerr << gettime(result) << std::endl;
        
        if (boost::regex_match(result, boost::regex("[0-9 :\-]*"))) {
            runtest.pass("gettime()");
        } else {
            runtest.fail("gettime())");
        }
    };
    
    ~Test() {};
};

int
main(int argc, char *argv[])
{
    int c;
    bool dump = false;
    char buffer[300];
    std::string filespec;
    
    int retries = 3;

    memset(buffer, 0, 300);
    
    while ((c = getopt (argc, argv, "hdvsm:")) != -1) {
        switch (c) {
          case 'h':
            usage ();
            break;
            
          case 'd':
            dump = true;
            break;
            
          case 's':
            waitforgdb = true;
            break;
                                                                                
          case 'v':
            verbosity++;
            break;
            
          default:
            usage ();
            break;
        }
    }
    
    Test test;
}

static void
usage (void)
{
    std::cerr << "This program tests the XML processing code." << std::endl;
    std::cerr << "Usage: ./xml [h]" << std::endl;
    std::cerr << "-h\tHelp" << std::endl;
    std::cerr << "-d\tDump parsed data" << std::endl;
    exit (-1);
}

